// GENERATED from the website's shared/decision-impact.ts by gen_impact.mts
// (from the web repo root: npx tsx gen_impact.mts <FinPlay root>). Do not edit by hand;
// regenerate when the web rules change (it also rewrites test/fixtures/decision_impact_golden.json).
// ignore_for_file: lines_longer_than_80_chars

part of 'decision_impact.dart';

/// Template model rates (TEMPLATE_RATES), keyed as in model_assumptions.
const Map<String, double> kTemplateRates = {
  'interestExpenseRate': 0.07,
  'interestIncomeRate': 0.05,
  'taxRate': 0.2,
  'depreciationRate': 0.1,
  'revenueMultiplier': 0.1,
  'marketingROI': 0.1,
  'inventoryWriteOffRate': 0.7,
  'capacityPerSarOfPpe': 5.0,
  'productivityPerMillion': 0.01,
  'productivityCap': 0.05,
  'marketingCarryOver': 0.5,
  'lifeMachinery': 5.0,
  'lifeBuildings': 25.0,
  'lifeAutomation': 7.0,
  'lifeTechnology': 3.0,
  'lifeNewRegion': 7.0,
  'lifeOpeningPpe': 10.0,
  'lifeIntangibles': 5.0,
  'eosbRateYears1to5': 0.041666666666666664,
  'eosbAccrualRateOfSalaryCost': 0.08333333333333333,
  'eosbRateMode': 1.0,
};

const Map<String, Bi> _statementNames = {
  'balance': Bi('Balance sheet', 'قائمة المركز المالي'),
  'income': Bi('Income statement', 'قائمة الدخل'),
  'cashflow': Bi('Cash flow', 'قائمة التدفقات النقدية'),
};

const Map<String, Bi> _cfNames = {
  'financing': Bi('financing activities', 'الأنشطة التمويلية'),
  'investing': Bi('investing activities', 'الأنشطة الاستثمارية'),
  'operating': Bi('operating activities', 'الأنشطة التشغيلية'),
};

const Map<String, Map<int, _Rule>> _rules = {
  'financing': {
    1: _Rule(
      bsAccount: Bi('Long-term bank loan', 'قرض بنكي طويل الأجل'),
      cashMoves: true,
      cf: 'financing',
      income: _InterestIncome(Bi('Interest expense', 'مصروف الفوائد')),
      meaningPlus: Bi('Borrowing: leverage rises and a fixed interest bill follows for ten years; cheaper than equity but it must be serviced in good years and bad.', 'اقتراض: يرتفع الرفع المالي وتلتزم الشركة بفوائد ثابتة لعشر سنوات؛ أرخص من حقوق الملكية لكنه يُسدَّد في السنوات الجيدة والسيئة.'),
      meaningMinus: Bi('Paying the loan down: less debt and less interest, at the cost of cash you could have invested.', 'سداد جزء من القرض: دين أقل وفوائد أقل، مقابل نقد كان يمكن استثماره.'),
    ),
    2: _Rule(
      bsAccount: Bi('Corporate bonds', 'سندات الشركة'),
      cashMoves: true,
      cf: 'financing',
      income: _InterestIncome(Bi('Coupon (interest) expense', 'مصروف الكوبون (الفائدة)')),
      meaningPlus: Bi('Issuing bonds: long-term debt from investors rather than a bank; leverage and the coupon bill rise, ownership does not change.', 'إصدار سندات: دين طويل الأجل من المستثمرين لا من البنك؛ يرتفع الرفع المالي وعبء الكوبون ولا تتغير الملكية.'),
      meaningMinus: Bi('Redeeming bonds: debt and coupons fall, cash leaves.', 'استرداد السندات: ينخفض الدين والكوبونات ويخرج النقد.'),
    ),
    3: _Rule(
      bsAccount: Bi('Short-term debt (current liability)', 'دين قصير الأجل (التزام متداول)'),
      cashMoves: true,
      cf: 'financing',
      income: _InterestIncome(Bi('Interest expense', 'مصروف الفوائد')),
      meaningPlus: Bi('A one-year loan: quick cash for working capital, but it falls due within the year, so the current ratio weakens.', 'قرض لسنة واحدة: نقد سريع لرأس المال العامل، لكنه يستحق خلال السنة فتضعف نسبة التداول.'),
      meaningMinus: Bi('Repaying short-term debt: current liabilities and interest fall; liquidity ratios improve.', 'سداد الدين قصير الأجل: تنخفض الالتزامات المتداولة والفوائد وتتحسن نسب السيولة.'),
    ),
    4: _Rule(
      bsAccount: Bi('Sukuk', 'الصكوك'),
      cashMoves: true,
      cf: 'financing',
      income: _InterestIncome(Bi('Sukuk profit distribution', 'توزيعات أرباح الصكوك')),
      meaningPlus: Bi('Issuing sukuk: Sharia-compliant financing that behaves like long-term debt in the statements; a fixed profit distribution replaces interest.', 'إصدار صكوك: تمويل متوافق مع الشريعة يُعامَل في القوائم كدين طويل الأجل؛ توزيع ربح ثابت بدلًا من الفائدة.'),
      meaningMinus: Bi('Redeeming sukuk: the obligation and its distributions fall, cash leaves.', 'استرداد الصكوك: ينخفض الالتزام وتوزيعاته ويخرج النقد.'),
    ),
    5: _Rule(
      bsAccount: Bi('Common stock (share capital)', 'رأس المال (الأسهم العادية)'),
      cashMoves: true,
      cf: 'financing',
      income: _FixedIncome(Bi('no interest; profit is spread over more shares, so earnings per share fall', 'لا فوائد؛ الربح يتوزع على عدد أكبر من الأسهم فتنخفض ربحية السهم'), Bi('no effect on profit; fewer shares outstanding, so earnings per share rise', 'لا أثر على الربح؛ عدد الأسهم يقل فترتفع ربحية السهم')),
      meaningPlus: Bi('Issuing shares: permanent capital with no repayment and no interest, paid for with dilution of existing owners.', 'إصدار أسهم: رأس مال دائم بلا سداد ولا فوائد، مقابل تخفيف حصة الملاك الحاليين.'),
      meaningMinus: Bi('Buying back shares (treasury shares): returns cash to owners and shrinks equity; the debt ratio rises.', 'إعادة شراء الأسهم (أسهم خزينة): إعادة نقد للملاك وتقليص حقوق الملكية؛ ترتفع نسبة الدين.'),
    ),
    6: _Rule(
      bsAccount: Bi('Retained earnings', 'الأرباح المبقاة'),
      cashMoves: false,
      cf: null,
      income: null,
      meaningPlus: Bi('Retained earnings are profits already kept in the business.', 'الأرباح المبقاة أرباح احتُفظ بها في الشركة أصلًا.'),
      meaningMinus: Bi('Using retained earnings is an appropriation inside equity (Dr Retained earnings / Cr General reserve): it earmarks past profits, it does not bring new cash, and it is capped at the opening retained earnings balance. It is not a dividend.', 'استخدام الأرباح المبقاة تخصيص داخل حقوق الملكية (من حـ/ الأرباح المبقاة إلى حـ/ الاحتياطي العام): يرصد أرباحًا سابقة ولا يجلب نقدًا جديدًا، ويقتصر على رصيد الأرباح المبقاة الافتتاحي. وليس توزيعًا للأرباح.'),
    ),
    7: _Rule(
      bsAccount: Bi('Additional capital (rights issue)', 'رأس مال إضافي (إصدار حقوق أولوية)'),
      cashMoves: true,
      cf: 'financing',
      income: _FixedIncome(Bi('no interest; more shares outstanding, so profit is spread more thinly', 'لا فوائد؛ يزداد عدد الأسهم فتتوزع الأرباح على قاعدة أوسع'), Bi('no interest; more shares outstanding, so profit is spread more thinly', 'لا فوائد؛ يزداد عدد الأسهم فتتوزع الأرباح على قاعدة أوسع')),
      meaningPlus: Bi('A rights issue: existing owners are offered new shares first, so dilution falls only on those who do not subscribe.', 'إصدار حقوق أولوية: تُعرض الأسهم الجديدة على الملاك الحاليين أولًا، فلا يقع التخفيف إلا على من لا يكتتب.'),
      meaningMinus: Bi('', ''),
    ),
    8: _Rule(
      bsAccount: Bi('Retained earnings', 'الأرباح المبقاة'),
      cashMoves: true,
      cf: 'financing',
      income: _FixedIncome(Bi('no effect on net income; dividends are taken from retained earnings after profit', 'لا أثر على صافي الربح؛ التوزيعات تُخصم من الأرباح المبقاة بعد الربح'), Bi('no effect on net income; dividends are taken from retained earnings after profit', 'لا أثر على صافي الربح؛ التوزيعات تُخصم من الأرباح المبقاة بعد الربح')),
      meaningPlus: Bi('', ''),
      meaningMinus: Bi('Paying dividends rewards shareholders now and lowers the cash and equity available to invest; markets read it as confidence, bankers read it as less cushion.', 'دفع التوزيعات يكافئ المساهمين الآن ويقلل النقد وحقوق الملكية المتاحة للاستثمار؛ السوق يقرؤها ثقة، والبنوك تقرؤها وسادة أقل.'),
    ),
    9: _Rule(
      bsAccount: Bi('Reserves', 'الاحتياطيات'),
      cashMoves: true,
      cf: 'financing',
      income: null,
      meaningPlus: Bi('', ''),
      meaningMinus: Bi('Drawing on reserves pays cash out of equity set aside in earlier years (Dr Reserves / Cr Cash); retained earnings are untouched, and the amount is capped at the opening reserves balance.', 'السحب من الاحتياطيات يدفع نقدًا من حقوق ملكية جُنِّبت في سنوات سابقة (من حـ/ الاحتياطيات إلى حـ/ النقد)؛ لا تتأثر الأرباح المبقاة، ويقتصر المبلغ على رصيد الاحتياطيات الافتتاحي.'),
    ),
  },
  'investing': {
    1: _Rule(
      bsAccount: Bi('Property, plant and equipment', 'الممتلكات والآلات والمعدات'),
      cashMoves: true,
      cf: 'investing',
      income: _CapexIncome(1),
      meaningPlus: Bi('Selling machinery: cash in and a smaller asset base; capacity to produce falls.', 'بيع آلات: نقد داخل وقاعدة أصول أصغر؛ تنخفض القدرة الإنتاجية.'),
      meaningMinus: Bi('Buying machinery: cash becomes a long-lived asset, expensed slowly as depreciation; it also lifts sales in the model.', 'شراء آلات: يتحول النقد إلى أصل طويل العمر يُصرف تدريجيًا كإهلاك؛ ويرفع المبيعات في النموذج.'),
    ),
    2: _Rule(
      bsAccount: Bi('Property, plant and equipment', 'الممتلكات والآلات والمعدات'),
      cashMoves: true,
      cf: 'investing',
      income: _CapexIncome(2),
      meaningPlus: Bi('', ''),
      meaningMinus: Bi('A new factory or office: a large, slow-payback asset; it adds depreciation for years and does not lift sales by itself in this model.', 'مصنع أو مكتب جديد: أصل كبير بطيء الاسترداد؛ يضيف إهلاكًا لسنوات ولا يرفع المبيعات بنفسه في هذا النموذج.'),
    ),
    3: _Rule(
      bsAccount: Bi('Property, plant and equipment', 'الممتلكات والآلات والمعدات'),
      cashMoves: true,
      cf: 'investing',
      income: _CapexIncome(3),
      meaningPlus: Bi('', ''),
      meaningMinus: Bi('Automation: capital spent now for capacity; depreciation follows, and the model rewards it with higher sales.', 'الأتمتة: إنفاق رأسمالي الآن مقابل قدرة إنتاجية؛ يتبعه إهلاك، ويكافئه النموذج بمبيعات أعلى.'),
    ),
    4: _Rule(
      bsAccount: Bi('Property, plant and equipment', 'الممتلكات والآلات والمعدات'),
      cashMoves: true,
      cf: 'investing',
      income: _CapexIncome(4),
      meaningPlus: Bi('', ''),
      meaningMinus: Bi('Technology infrastructure: capitalised, then depreciated; it does not lift sales by itself in this model.', 'البنية التقنية: تُرسمل ثم تُهلك؛ ولا ترفع المبيعات بنفسها في هذا النموذج.'),
    ),
    5: _Rule(
      bsAccount: Bi('Property, plant and equipment', 'الممتلكات والآلات والمعدات'),
      cashMoves: true,
      cf: 'investing',
      income: _CapexIncome(5),
      meaningPlus: Bi('', ''),
      meaningMinus: Bi('Opening in a new region: assets and depreciation now, revenue later and uncertain; the riskiest of the capital decisions.', 'التوسع في منطقة جديدة: أصول وإهلاك الآن، وإيراد لاحق وغير مؤكد؛ أكثر القرارات الرأسمالية مخاطرة.'),
    ),
    6: _Rule(
      bsAccount: Bi('Investments (securities)', 'الاستثمارات (أوراق مالية)'),
      cashMoves: true,
      cf: 'investing',
      income: _FixedIncome(Bi('no depreciation and no operating revenue; the return shows on sale or as income from the issuer', 'لا إهلاك ولا إيراد تشغيلي؛ العائد يظهر عند البيع أو من توزيعات المُصدِر'), Bi('no depreciation and no operating revenue; the return shows on sale or as income from the issuer', 'لا إهلاك ولا إيراد تشغيلي؛ العائد يظهر عند البيع أو من توزيعات المُصدِر')),
      meaningPlus: Bi('Selling securities: cash in, investments down.', 'بيع أوراق مالية: نقد داخل واستثمارات أقل.'),
      meaningMinus: Bi('Buying other companies’ securities: cash parked outside the business; liquid, but it does not grow your own operations.', 'شراء أوراق مالية لشركات أخرى: نقد موضوع خارج النشاط؛ سائل لكنه لا ينمّي عملياتك.'),
    ),
    7: _Rule(
      bsAccount: Bi('Investments (joint ventures)', 'الاستثمارات (مشاريع مشتركة)'),
      cashMoves: true,
      cf: 'investing',
      income: _FixedIncome(Bi('no depreciation; the venture’s share of profit shows when it earns it', 'لا إهلاك؛ حصة أرباح المشروع المشترك تظهر عندما يحققها'), Bi('no depreciation; the venture’s share of profit shows when it earns it', 'لا إهلاك؛ حصة أرباح المشروع المشترك تظهر عندما يحققها')),
      meaningPlus: Bi('Divesting a venture: cash in, investments down.', 'التخارج من مشروع مشترك: نقد داخل واستثمارات أقل.'),
      meaningMinus: Bi('A joint venture: shared capital and shared control; slower than owning the asset, cheaper than buying it alone.', 'مشروع مشترك: رأس مال مشترك وسيطرة مشتركة؛ أبطأ من امتلاك الأصل وأرخص من شرائه منفردًا.'),
    ),
    8: _Rule(
      bsAccount: Bi('Intangible assets and goodwill', 'الأصول غير الملموسة والشهرة'),
      cashMoves: true,
      cf: 'investing',
      income: _AmortizationIncome(),
      meaningPlus: Bi('', ''),
      meaningMinus: Bi('Buying intangibles (licences, brands, software rights): an asset you cannot see, amortised over its life; value depends on use, not resale.', 'شراء أصول غير ملموسة (تراخيص، علامات، حقوق برمجيات): أصل لا يُرى يُطفأ على عمره؛ قيمته في الاستخدام لا في إعادة البيع.'),
    ),
    9: _Rule(
      bsAccount: Bi('Investments (acquisition)', 'الاستثمارات (استحواذ)'),
      cashMoves: true,
      cf: 'investing',
      income: _FixedIncome(Bi('no depreciation in this model; the real effect comes from the market share acquired', 'لا إهلاك في هذا النموذج؛ الأثر الحقيقي يأتي من الحصة السوقية المكتسبة'), Bi('no depreciation in this model; the real effect comes from the market share acquired', 'لا إهلاك في هذا النموذج؛ الأثر الحقيقي يأتي من الحصة السوقية المكتسبة')),
      meaningPlus: Bi('', ''),
      meaningMinus: Bi('Acquiring a competitor: the biggest bet on the board; market share now, integration risk later.', 'الاستحواذ على منافس: أكبر رهان على الطاولة؛ حصة سوقية الآن ومخاطر دمج لاحقًا.'),
    ),
  },
  'operating': {
    1: _Rule(
      bsAccount: Bi('No balance-sheet account: expensed in the year', 'لا حساب في المركز المالي: يُصرف في السنة'),
      cashMoves: true,
      cf: 'operating',
      income: _OpexIncome(true),
      meaningPlus: Bi('Cutting the campaign saves cost this year and gives up the sales it would have brought.', 'خفض الحملة يوفر تكلفة هذا العام ويتنازل عن المبيعات التي كانت ستجلبها.'),
      meaningMinus: Bi('Marketing is an expense now for revenue now; it pays only if the sales it brings carry more margin than it costs.', 'التسويق مصروف الآن مقابل إيراد الآن؛ يجدي فقط إذا حملت المبيعات التي يجلبها هامشًا يفوق كلفته.'),
    ),
    2: _Rule(
      bsAccount: Bi('End-of-service benefits provision', 'مخصص مكافأة نهاية الخدمة'),
      cashMoves: true,
      cf: 'operating',
      income: _StaffIncome(false),
      meaningPlus: Bi('Laying off staff cuts salaries now; their end-of-service benefit is paid out of the provision and capability is lost.', 'تسريح الموظفين يخفض الرواتب الآن؛ تُدفع مكافأة نهاية خدمتهم من المخصص وتُفقد القدرات.'),
      meaningMinus: Bi('Hiring technical staff: a salary bill plus an end-of-service benefit accruing at half a month per year of service (Labour Law Article 84); capacity to deliver rises.', 'توظيف كوادر فنية: رواتب متكررة والتزام نهاية خدمة متنامٍ؛ ترتفع القدرة على الإنجاز.'),
    ),
    3: _Rule(
      bsAccount: Bi('No balance-sheet account: expensed in the year', 'لا حساب في المركز المالي: يُصرف في السنة'),
      cashMoves: true,
      cf: 'operating',
      income: _OpexIncome(false),
      meaningPlus: Bi('Cutting training saves cost now at the expense of skills later.', 'خفض التدريب يوفر التكلفة الآن على حساب المهارات لاحقًا.'),
      meaningMinus: Bi('Training is expensed, never capitalised, even though its benefit lasts; accounting is conservative about people.', 'التدريب يُصرف ولا يُرسمل رغم أن نفعه يدوم؛ المحاسبة متحفظة تجاه الاستثمار في الناس.'),
    ),
    4: _Rule(
      bsAccount: Bi('No balance-sheet account: expensed in the year', 'لا حساب في المركز المالي: يُصرف في السنة'),
      cashMoves: true,
      cf: 'operating',
      income: _OpexIncome(false),
      meaningPlus: Bi('Controlling utilities, rent and supplies lifts operating profit one for one: the cheapest profit there is.', 'ضبط المرافق والإيجار والمستلزمات يرفع الربح التشغيلي ريالًا بريال: أرخص ربح ممكن.'),
      meaningMinus: Bi('Higher overheads reduce operating profit one for one.', 'ارتفاع المصروفات العامة يخفض الربح التشغيلي ريالًا بريال.'),
    ),
    5: _Rule(
      bsAccount: Bi('No balance-sheet account: expensed in the year', 'لا حساب في المركز المالي: يُصرف في السنة'),
      cashMoves: true,
      cf: 'operating',
      income: _OpexIncome(false),
      meaningPlus: Bi('', ''),
      meaningMinus: Bi('Quality standards and inspections cost now and prevent rework, returns and reputational loss later.', 'معايير الجودة والتفتيش تكلف الآن وتمنع إعادة العمل والمرتجعات وخسارة السمعة لاحقًا.'),
    ),
    6: _Rule(
      bsAccount: Bi('No balance-sheet account: expensed in the year', 'لا حساب في المركز المالي: يُصرف في السنة'),
      cashMoves: true,
      cf: 'operating',
      income: _OpexIncome(false),
      meaningPlus: Bi('', ''),
      meaningMinus: Bi('Handling complaints is a cost of keeping customers; unhandled complaints cost sales you never see.', 'معالجة الشكاوى تكلفة للاحتفاظ بالعملاء؛ الشكاوى المهملة تكلف مبيعات لا تراها.'),
    ),
    7: _Rule(
      bsAccount: Bi('No balance-sheet account: expensed in the year', 'لا حساب في المركز المالي: يُصرف في السنة'),
      cashMoves: true,
      cf: 'operating',
      income: _OpexIncome(false),
      meaningPlus: Bi('', ''),
      meaningMinus: Bi('Operational software here is expensed, not capitalised; it hits profit at once and pays back through efficiency you must earn.', 'البرمجيات التشغيلية هنا تُصرف ولا تُرسمل؛ تؤثر في الربح فورًا وتسترد نفسها بكفاءة عليك تحقيقها.'),
    ),
    8: _Rule(
      bsAccount: Bi('End-of-service benefits provision', 'مخصص مكافأة نهاية الخدمة'),
      cashMoves: true,
      cf: 'operating',
      income: _StaffIncome(true),
      meaningPlus: Bi('', ''),
      meaningMinus: Bi('Hiring sales professionals: salaries and an end-of-service liability now, revenue growth that the model rewards.', 'توظيف مندوبي مبيعات: رواتب والتزام نهاية خدمة الآن، ونمو إيراد يكافئه النموذج.'),
    ),
    9: _Rule(
      bsAccount: Bi('Inventory', 'المخزون'),
      cashMoves: true,
      cf: 'operating',
      income: _InventoryIncome(),
      meaningPlus: Bi('', ''),
      meaningMinus: Bi('Buying inventory turns cash into stock: an asset, not an expense, until it sells; it ties up working capital and carries holding and obsolescence risk.', 'شراء المخزون يحول النقد إلى بضاعة؛ يجمّد رأس المال العامل ويحمل مخاطر التخزين والتقادم حتى يُباع.'),
    ),
  },
};
